---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/az/Desktop/sinfool/Sandbox6/SearchBarCustomPlaceholderTextColorieSettingsSearchetc/.theos/obj/arm64/SearchBarCustomPlaceholderTextColorieSettingsSearchetc.dylib'
relocations:
  - { offsetInCU: 0x1E, offset: 0x1E, size: 0x8, addend: 0x0, symName: __ZL15_logosLocalInitv, symObjAddr: 0x0, symBinAddr: 0x4000, symSize: 0x34 }
  - { offsetInCU: 0x4A, offset: 0x4A, size: 0x8, addend: 0x0, symName: '__ZL62_logos_orig$_ungrouped$UISearchBarTextFieldLabel$setTextColor$', symObjAddr: 0x8F8, symBinAddr: 0xC018, symSize: 0x0 }
  - { offsetInCU: 0xCA, offset: 0xCA, size: 0x8, addend: 0x0, symName: __ZL15_logosLocalInitv, symObjAddr: 0x0, symBinAddr: 0x4000, symSize: 0x34 }
  - { offsetInCU: 0x111, offset: 0x111, size: 0x8, addend: 0x0, symName: '__ZL64_logos_method$_ungrouped$UISearchBarTextFieldLabel$setTextColor$P25UISearchBarTextFieldLabelP13objc_selectorP11objc_object', symObjAddr: 0x34, symBinAddr: 0x4034, symSize: 0x54 }
  - { offsetInCU: 0x157, offset: 0x157, size: 0x8, addend: 0x0, symName: '__ZL64_logos_method$_ungrouped$UISearchBarTextFieldLabel$setTextColor$P25UISearchBarTextFieldLabelP13objc_selectorP11objc_object', symObjAddr: 0x34, symBinAddr: 0x4034, symSize: 0x54 }
...
