ARCHS = arm64 arm64e
TARGET = iphone:clang:14.5:14.5
DEBUG = 0

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ColorCustomierv241
ColorCustomierv241_FILES = Tweak.mm
ColorCustomierv241_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
